import React, { useState } from 'react';
import { Box } from '@mui/material';
import DataTable from '../DataTable/DataTable';
import DetailDialog from '../common/DetailDialog';

const statusColor = (s) => s === 'published' ? 'success' : s === 'draft' ? 'warning' : 'default';
const typeColor = (t) => ({ analytics: 'info', performance: 'primary', usage: 'secondary', financial: 'success' }[t] || 'default');

const columns = [
  { field: 'title', label: 'Title', sortable: true },
  { field: 'type', label: 'Type', chip: true, chipColor: typeColor, sortable: true },
  { field: 'status', label: 'Status', chip: true, chipColor: statusColor, sortable: true },
  { field: 'created_at', label: 'Created', sortable: true, render: (v) => new Date(v).toLocaleDateString() },
];

const detailFields = [
  { key: 'title', label: 'Title', dbField: 'title', editable: true },
  { key: 'description', label: 'Description', dbField: 'description', editable: true, multiline: true, fullWidth: true },
  { key: 'type', label: 'Type', dbField: 'type', chip: true, chipColor: typeColor, editable: true, type: 'select', options: ['analytics', 'performance', 'usage', 'financial'] },
  { key: 'status', label: 'Status', dbField: 'status', chip: true, chipColor: statusColor, editable: true, type: 'select', options: ['draft', 'published', 'archived'] },
  { key: 'data', label: 'Data', dbField: 'data', fullWidth: true, render: (v) => { try { return JSON.stringify(JSON.parse(v), null, 2); } catch { return v || 'None'; } } },
  { key: 'agent_id', label: 'Agent ID', dbField: 'agent_id' },
  { key: 'generated_by', label: 'Generated By', dbField: 'generated_by' },
  { key: 'created_at', label: 'Created', dbField: 'created_at', render: (v) => new Date(v).toLocaleString() },
];

const filterOptions = {
  type: { label: 'Type', values: ['analytics', 'performance', 'usage', 'financial'] },
  status: { label: 'Status', values: ['draft', 'published', 'archived'] },
};

export default function ReportsPage() {
  const [selected, setSelected] = useState(null);
  const [refresh, setRefresh] = useState(0);

  return (
    <Box sx={{ p: { xs: 1, sm: 3 } }}>
      <DataTable key={refresh} entity="reports" columns={columns} title="Reports" filterOptions={filterOptions}
        onRowClick={(row) => setSelected(row)} onEdit={(row) => setSelected(row)} />
      <DetailDialog open={!!selected} item={selected} entity="reports" fields={detailFields}
        onClose={() => setSelected(null)} onUpdate={() => { setSelected(null); setRefresh(r => r + 1); }}
        onDelete={() => { setSelected(null); setRefresh(r => r + 1); }} />
    </Box>
  );
}
